### ISSUE TITLE
Build / emulate

### ISSUE THREAD

**Issue by kjetilhp** [snorreks/nx-cloud-functions-deployer#1]
Hi, how are the development process supposed to work with this sctructure? Looking at the code I see that you have an emulate target but it is not documentet, the same with build. Am I supposed to keep a separate firebase.json to emulate all the functions at once? And build using deploy --dry? (the build target seem to have some issues with paths when called directly)

**Comment by snorreks** [comment]
Should be working now in 2.5.0, see the [example](https://github.com/snorreks/nx-cloud-functions-deployer/blob/master/example/apps/functions/project.json)
